version: "3"

services:
  database:
    build: Database
    volumes:
      - ./Database/data:/var/lib/postgresql/data
  email:
    build: Email
    deploy:
      replicas: 1
    volumes:
      - ./env:/env
  profile:
    build: Profile
    depends_on: [database,email]
    deploy:
      replicas: 5
    volumes:
      - ./env:/env
      - ./Database:/Database
      - ./profilePictures:/profilePictures

  mart:
    build: Mart
    depends_on: [database,email]
    deploy:
      replicas: 5
    volumes:
      - ./env:/env
      - ./Database:/Database


  reverse-proxy:
    build: nginx
    depends_on: [profile, mart]
    ports:
      - 80:80
      - 443:443

    volumes:
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/data:/var/www/certbot
