version: "3"

services:
  database:
    build: Database
    volumes:
      - ./Database/data:/var/lib/postgresql/data

  rpay-database:
    build: rPay/Database
    volumes:
      - ./rPay/Database/data:/var/lib/postgresql/data

  redis:
    command: redis-server --requirepass rec@3214-initators|database|~reDiS|||cAchE
    image: redis

  email:
    build: Email
    deploy:
      replicas: 1
    volumes:
      - ./env:/env
      - ./Mart/QrImages:/QrImages

  jobs:
    build: jobs
    depends_on: [database, email]
    deploy:
      replicas: 1
    volumes:
      - ./env:/env
      - ./Database:/Database

  profile:
    build: Profile
    depends_on: [database, email, redis]
    deploy:
      replicas: 5
    volumes:
      - ./env:/env
      - ./Database:/Database
      - ./cache:/cache
      - ./profilePictures:/profilePictures

  block:
    build: rPay/Block
    depends_on: [rpay-database]
    volumes:
      - ./env:/env
      - ./rPay/Database:/Database

  rpay-profile:
    build: rPay/Profile
    depends_on: [block, rpay-database]
    volumes:
      - ./env:/env
      - ./rPay/Database:/Database
      - ./rPay/profilePictures:/profilePictures

  admin:
    build: rPay/Admin
    ports:
      - 4500:4500
    volumes:
      - ./env:/env
      - ./rPay/Database:/Database

  transaction:
    build: rPay/Transaction
    depends_on: [block, rpay-database]
    volumes:
      - ./env:/env
      - ./rPay/Database:/Database

  sync:
    build: rPay/Sync
    volumes:
      - ./env:/env
      - ./rPay/Database:/Database

  console:
    build: rPay/Console

  mart:
    build: Mart
    depends_on: [database, email, redis]
    deploy:
      replicas: 5
    volumes:
      - ./env:/env
      - ./Database:/Database
      - ./cache:/cache
      - ./Mart/QrImages:/QrImages

  reverse-proxy:
    build: nginx
    depends_on: [profile, mart, rpay-profile, transaction, sync, admin, console]
    ports:
      - 80:80
      - 443:443

    volumes:
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/data:/var/www/certbot

  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/certbot --email 2017ashwin@gmail.com --agree-tos --no-eff-email -d www.rajalakshmipay.com -d www.rajalakshmipay.com -2
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/logs:/var/log/letsencrypt
      - ./certbot/data:/var/www/certbot
