version: "3"

services:
  database:
    build: Database
    volumes:
      - ./Database/data:/var/lib/postgresql/data

  rpay-database:
    build: rPay/Database
    volumes:
      - ./rPay/Database/data:/var/lib/postgresql/data

  redis:
      command: redis-server --requirepass rec@3214-initators|database|~reDiS|||cAchE
      image: redis

  email:
    build: Email
    deploy:
      replicas: 1
    volumes:
      - ./env:/env
      - ./Mart/QrImages:/QrImages

  jobs:
    build: jobs
    depends_on: [database,email]
    deploy:
      replicas: 1
    volumes:
      - ./env:/env
      - ./Database:/Database

  profile:
    build: Profile
    depends_on: [database,email,redis]
    deploy:
      replicas: 5
    volumes:
      - ./env:/env
      - ./Database:/Database
      - ./cache:/cache
      - ./profilePictures:/profilePictures
  
  block:
    build: Block
    depends_on: [rpay-database]
    volumes:
      - ./env:/env
      - ./rPay/Database:/Database

  rpay-profile:
    build: Profile
    depends_on: [block,rpay-database]
    volumes:
      - ./env:/env
      - ./rPay/Database:/Database
      - ./rPay/profilePictures:/profilePictures
  
  transaction:
    build: Transaction
    depends_on: [block,rpay-database]
    volumes:
      - ./env:/env
      - ./rPay/Database:/Database

  mart:
    build: Mart
    depends_on: [database,email,redis]
    deploy:
      replicas: 5
    volumes:
      - ./env:/env
      - ./Database:/Database
      - ./cache:/cache
      - ./Mart/QrImages:/QrImages


  reverse-proxy:
    build: nginx
    depends_on: [profile, mart]
    ports:
      - 80:80
      - 443:443

    volumes:
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/data:/var/www/certbot
