version: "3"

services:
  database:
    build: Database
    # ports:
    #   - 5432:5432
    volumes:
      - ./Database/data:/var/lib/postgresql/data
  profile:
    build: Profile
    depends_on: [database]
    # ports:
    #   - 8000:8000
    deploy:
      replicas: 5
    volumes:
      - ./env:/env
      - ./Database:/Database
      - ./profilePictures:/profilePictures

  mart:
    build: Mart
    depends_on: [database]
    deploy:
      replicas: 5
    # ports:
    #   - 4600:4600
    volumes:
      - ./env:/env
      - ./Database:/Database


  reverse-proxy:
    build: nginx
    depends_on: [profile, mart]
    ports:
      - 80:80
      - 443:443

    volumes:
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/data:/var/www/certbot
