true = True
false = False
products = [{
        "productID": 1,
        "productName": "Pongal",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "breakfast",
        "price": 20,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "pongal.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 2,
        "productName": "Idli (1 No)",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "breakfast",
        "price": 5,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "idly_vada.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 3,
        "productName": "Poori (1 Nos)",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "breakfast",
        "price": 10,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "poori.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 4,
        "productName": "Chola Poori (1 Nos)",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "breakfast",
        "price": 30,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "cholapuri.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 5,
        "productName": "Nice Dosa (1 Nos)",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "breakfast",
        "price": 20,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "nicedosa.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 6,
        "productName": "Onion Dosa (1 Nos)",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "breakfast",
        "price": 30,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "onion_dosa.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 7,
        "productName": "Masala Dosa (1 Nos)",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "breakfast",
        "price": 30,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "masaladosa.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 8,
        "productName": "Kal dosa (1 Nos)",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "breakfast",
        "price": 10,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "kal_dosai.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 9,
        "productName": "Egg Dosa (1 Nos)",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "breakfast",
        "price": 30,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "egg_dosai.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 10,
        "productName": "Ghee Roast (1 Nos)",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "breakfast",
        "price": 30,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "gheeroast.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 11,
        "productName": "vada (1 Nos)",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "breakfast",
        "price": 10,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "vada.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 12,
        "productName": "Chapatti (1 Nos)",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "lunch",
        "price": 11,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "chapatti.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 13,
        "productName": "paratha (1 Nos)",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "lunch",
        "price": 10,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "paratta.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 14,
        "productName": "Chilli paratha",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "lunch",
        "price": 50,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "chilli_parata.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    }, {
        "productID": 15,
        "productName": "Meals",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "lunch",
        "price": 40,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "meals.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 16,
        "productName": "Veg Fried Rice",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "lunch",
        "price": 40,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "veg_friedrice.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 17,
        "productName": "Egg Fried Rice",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "lunch",
        "price": 50,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "egg_friedrice.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 18,
        "productName": "Gobi Fried Rice",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "lunch",
        "price": 50,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "gobirice.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 19,
        "productName": "Veg Noodles",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "lunch",
        "price": 40,
        "discount": 0,
        "isavailable": true,
        "quantity": 52,
        "imageUrl": "vegnoodles.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 20,
        "productName": "Egg Noodles",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "lunch",
        "price": 50,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "eggnoodle.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 21,
        "productName": "Gobi Noodles",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "lunch",
        "price": 50,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "gobinoodle.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 22,
        "productName": "Veg Biriyani",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "lunch",
        "price": 40,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "veg_biriyani.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 23,
        "productName": "Egg Biriyani",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "lunch",
        "price": 50,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "egg_biriyani.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 24,
        "productName": "Sambar Rice",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "lunch",
        "price": 30,
        "discount": 0,
        "isavailable": false,
        "quantity": 50,
        "imageUrl": "sambar_rice.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 25,
        "productName": "Curd Rice",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "lunch",
        "price": 30,
        "discount": 0,
        "isavailable": false,
        "quantity": 50,
        "imageUrl": "lemon_rice.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 26,
        "productName": "Omelette",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "lunch",
        "price": 15,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "omelette.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 27,
        "productName": "Boiled Egg",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "lunch",
        "price": 10,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "boiled_egg.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 28,
        "productName": "Rose Milk",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 20,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "rosemilk.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 29,
        "productName": "Lemon Juice",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 15,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "lemonjuice.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 30,
        "productName": "Samosa(1 Nos)",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "snacks",
        "price": 10,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "samosa.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 31,
        "productName": "Bread Omelette",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "snacks",
        "price": 30,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "bread_omelette.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 32,
        "productName": "Veg Roll(1 Nos)",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "snacks",
        "price": 20,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "veg_roll.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 33,
        "productName": "Egg Roll (1 Nos)",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "snacks",
        "price": 30,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "egg_roll.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 34,
        "productName": "Veg Puff (1 Nos)",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "snacks",
        "price": 15,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "veg_puff.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 35,
        "productName": "Egg Puff(1 Nos)",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "snacks",
        "price": 20,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "egg_puff.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 36,
        "productName": "Corn Puffs",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 10,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "cornpuff.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 37,
        "productName": "Water Bottle (500 ML)",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 10,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "water_bottle.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 38,
        "productName": "Milk Shake",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 35,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "shake.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 39,
        "productName": "Too Yum (All Flavours)",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 10,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "yum.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 40,
        "productName": "Chola Poori (1 Nos)",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "lunch",
        "price": 30,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "cholapuri.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 41,
        "productName": "Podi Dosai",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "breakfast",
        "price": 25,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "podi_dosai.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 42,
        "productName": "Tea",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 10,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "tea.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 43,
        "productName": "Cofee",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 10,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "cofee.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 44,
        "productName": "Unibic Cookies",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 10,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "unibic_cookie.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 45,
        "productName": "Cup Cake",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 20,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "cup_cake.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 46,
        "productName": "Bajji",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "snacks",
        "price": 10,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "bajji.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 47,
        "productName": "Maa",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 20,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "maa.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 48,
        "productName": "Maa",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 10,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "maa_10.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 49,
        "productName": "Cadbury Choco Bakes",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 10,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "cadbury_chocobakes.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 50,
        "productName": "cadbury Silk Rosted Almond",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 80,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "silk_rosted_almond.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 51,
        "productName": "cadbury Dairy Milk Fruit & Nut",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 45,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "dairymilk_fruit&nut.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 52,
        "productName": "cadbury Silk bubbly bubble Gum",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 80,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "silk_rosted_almond.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 53,
        "productName": "Hide & Seek",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 10,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "hide&seek.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 54,
        "productName": "Oreo Dipped",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 25,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "oreo_dipped.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 55,
        "productName": "Hide & Seek",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 30,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "hide&seek.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 56,
        "productName": "Milano",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 30,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "milano.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 57,
        "productName": "Cadbury Fuse",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 20,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "fuse.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 57,
        "productName": "cadbury Dairy Milk Crackle",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 45,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "dairymilk_crackle.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 58,
        "productName": "cadbury Dairy Milk Crispello",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 45,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "dairymilk_crispello.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 59,
        "productName": "5 Star",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 10,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "5star.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 60,
        "productName": "Cavins Mango Lassi ",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 25,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "cavins_mango_lassi.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 61,
        "productName": "Cavins Stawberry Lassi ",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 20,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "cavins_strawberry_lassi.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 62,
        "productName": "20-20 Nice",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 10,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "20-20_nice.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 63,
        "productName": "Cadbury Bourn Vita ",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 10,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "bournvita.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 64,
        "productName": "Pappai Kulfi",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 30,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "kulfi.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 65,
        "productName": "Pappai Fun Blast Heavy",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 50,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "funblast_cup.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 66,
        "productName": "Pappai Fun Blast",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 30,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "funblast_cup.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 67,
        "productName": "Pappai Cornado",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 40,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "bscone.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 68,
        "productName": "Pappai Choco Bar",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 30,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "chocobar.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 69,
        "productName": "Pappai Cup",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 30,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "pappai_cup1.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 70,
        "productName": "Pappai Kulfi",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 35,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "kulfi.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 71,
        "productName": "Pappai Milky Den",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 25,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "milky_den.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 72,
        "productName": "Sip Up",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 5,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "sipup.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 73,
        "productName": "Choco Bar",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 10,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "chocobar.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 74,
        "productName": "Papai cup",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 10,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "papai_cup.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 75,
        "productName": "Papai Cup",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 20,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "papai_cup.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 76,
        "productName": "Cone ",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 10,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "bscone1.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 77,
        "productName": "Cone",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 20,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "bscone2.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    },
    {
        "productID": 78,
        "productName": "cone",
        "ownerID": "rbusiness@919704755328",
        "discription": "from REC Cafe",
        "category": "others",
        "price": 30,
        "discount": 0,
        "isavailable": true,
        "quantity": 50,
        "imageUrl": "bscone3.png",
        "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
    }



]