true = True
products = [{
    "productID": 1,
    "productName": "Pongal",
    "ownerID": "rbusiness@919840573702",
    "discription": "from REC Cafe",
    "category": "breakfast",
    "price": 20,
    "discount":0,
    "isavailable": true,
    "quantity": 50,
    "imageUrl": "pongal.png",
    "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
},
{
    "productID": 2,
    "productName": "Idli (1 No)",
    "ownerID": "rbusiness@919840573702",
    "discription": "from REC Cafe",
    "category": "breakfast",
    "price": 5,
    "discount":0,
    "isavailable": true,
    "quantity": 50,
    "imageUrl": "idly_vada.png",
    "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
},
{
    "productID": 3,
    "productName": "Poori (1 Nos)",
    "ownerID": "rbusiness@919840573702",
    "discription": "from REC Cafe",
    "category": "breakfast",
    "price": 10,
    "discount":0,
    "isavailable": true,
    "quantity": 50,
    "imageUrl": "poori.png",
    "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
},
{
    "productID": 4,
    "productName": "Chola Poori (1 Nos)",
    "ownerID": "rbusiness@919840573702",
    "discription": "from REC Cafe",
    "category": "breakfast",
    "price": 30,
    "discount":0,
    "isavailable": true,
    "quantity": 50,
    "imageUrl": "cholapuri.png",
    "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
},
{
    "productID": 5,
    "productName": "Nice Dosa (1 Nos)",
    "ownerID": "rbusiness@919840573702",
    "discription": "from REC Cafe",
    "category": "breakfast",
    "price": 20,
    "discount":0,
    "isavailable": true,
    "quantity": 50,
    "imageUrl": "nicedosa.png",
    "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
},
{
    "productID": 6,
    "productName": "Onion Dosa (1 Nos)",
    "ownerID": "rbusiness@919840573702",
    "discription": "from REC Cafe",
    "category": "breakfast",
    "price": 30,
    "discount":0,
    "isavailable": true,
    "quantity": 50,
    "imageUrl": "onion_dosa.png",
    "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
},
{
    "productID": 7,
    "productName": "Masala Dosa (1 Nos)",
    "ownerID": "rbusiness@919840573702",
    "discription": "from REC Cafe",
    "category": "breakfast",
    "price": 30,
    "discount":0,
    "isavailable": true,
    "quantity": 50,
    "imageUrl": "masaladosa.png",
    "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
},
{
    "productID": 8,
    "productName": "Kal dosa (1 Nos)",
    "ownerID": "rbusiness@919840573702",
    "discription": "from REC Cafe",
    "category": "breakfast",
    "price": 10,
    "discount":0,
    "isavailable": true,
    "quantity": 50,
    "imageUrl": "kal_dosai.png",
    "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
},
{
    "productID": 9,
    "productName": "Egg Dosa (1 Nos)",
    "ownerID": "rbusiness@919840573702",
    "discription": "from REC Cafe",
    "category": "breakfast",
    "price": 30,
    "discount":0,
    "isavailable": true,
    "quantity": 50,
    "imageUrl": "egg_dosai.png",
    "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
},
{
    "productID": 10,
    "productName": "Ghee Roast (1 Nos)",
    "ownerID": "rbusiness@919840573702",
    "discription": "from REC Cafe",
    "category": "breakfast",
    "price": 30,
    "discount":0,
    "isavailable": true,
    "quantity": 50,
    "imageUrl": "gheeroast.png",
    "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
},
{
    "productID": 11,
    "productName": "vada (1 Nos)",
    "ownerID": "rbusiness@919840573702",
    "discription": "from REC Cafe",
    "category": "breakfast",
    "price": 10,
    "discount":0,
    "isavailable": true,
    "quantity": 50,
    "imageUrl": "vada.png",
    "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
},
{
    "productID": 12,
    "productName": "Chapatti (1 Nos)",
    "ownerID": "rbusiness@919840573702",
    "discription": "from REC Cafe",
    "category": "lunch",
    "price": 10,
    "discount":0,
    "isavailable": true,
    "quantity": 50,
    "imageUrl": "chapatti.png",
    "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
},
{
    "productID": 13,
    "productName": "paratha (1 Nos)",
    "ownerID": "rbusiness@919840573702",
    "discription": "from REC Cafe",
    "category": "lunch",
    "price": 10,
    "discount":0,
    "isavailable": true,
    "quantity": 50,
    "imageUrl": "paratta.png",
    "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
},
{
    "productID": 14,
    "productName": "Chilli paratha",
    "ownerID": "rbusiness@919840573702",
    "discription": "from REC Cafe",
    "category": "lunch",
    "price": 50,
    "discount":0,
    "isavailable": true,
    "quantity": 50,
    "imageUrl": "chilli_parata.png",
    "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
}, {
    "productID": 15,
    "productName": "Meals",
    "ownerID": "rbusiness@919840573702",
    "discription": "from REC Cafe",
    "category": "lunch",
    "price": 40,
    "discount":0,
    "isavailable": true,
    "quantity": 50,
    "imageUrl": "meals.png",
    "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
},
{
    "productID": 16,
    "productName": "Veg Fried Rice",
    "ownerID": "rbusiness@919840573702",
    "discription": "from REC Cafe",
    "category": "lunch",
    "price": 40,
    "discount":0,
    "isavailable": true,
    "quantity": 50,
    "imageUrl": "veg_friedrice.png",
    "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
},
{
    "productID": 17,
    "productName": "Egg Fried Rice",
    "ownerID": "rbusiness@919840573702",
    "discription": "from REC Cafe",
    "category": "lunch",
    "price": 50,
    "discount":0,
    "isavailable": true,
    "quantity": 50,
    "imageUrl": "egg_friedrice.png",
    "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
},
{
    "productID": 18,
    "productName": "Gobi Fried Rice",
    "ownerID": "rbusiness@919840573702",
    "discription": "from REC Cafe",
    "category": "lunch",
    "price": 50,
    "discount":0,
    "isavailable": true,
    "quantity": 50,
    "imageUrl": "gobirice.png",
    "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
},
{
    "productID": 19,
    "productName": "Veg Noodles",
    "ownerID": "rbusiness@919840573702",
    "discription": "from REC Cafe",
    "category": "lunch",
    "price": 40,
    "discount":0,
    "isavailable": true,
    "quantity": 50,
    "imageUrl": "vegnoodles.png",
    "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
},
{
    "productID": 20,
    "productName": "Egg Noodles",
    "ownerID": "rbusiness@919840573702",
    "discription": "from REC Cafe",
    "category": "lunch",
    "price": 50,
    "discount":0,
    "isavailable": true,
    "quantity": 50,
    "imageUrl": "eggnoodle.png",
    "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
},
{
    "productID": 21,
    "productName": "Gobi Noodlew",
    "ownerID": "rbusiness@919840573702",
    "discription": "from REC Cafe",
    "category": "lunch",
    "price": 50,
    "discount":0,
    "isavailable": true,
    "quantity": 50,
    "imageUrl": "gobinoodle.png",
    "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
}, 
{
    "productID": 22,
    "productName": "Veg Biriyani",
    "ownerID": "rbusiness@919840573702",
    "discription": "from REC Cafe",
    "category": "lunch",
    "price": 40,
    "discount":0,
    "isavailable": true,
    "quantity": 50,
    "imageUrl": "veg_biriyani.png",
    "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
},
{
    "productID": 23,
    "productName": "Egg Biriyani",
    "ownerID": "rbusiness@919840573702",
    "discription": "from REC Cafe",
    "category": "lunch",
    "price": 50,
    "discount":0,
    "isavailable": true,
    "quantity": 50,
    "imageUrl": "egg_biriyani.png",
    "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
},
{
    "productID": 24,
    "productName": "Sambar Rice",
    "ownerID": "rbusiness@919840573702",
    "discription": "from REC Cafe",
    "category": "lunch",
    "price": 30,
    "discount":0,
    "isavailable": true,
    "quantity": 50,
    "imageUrl": "sambar_rice.png",
    "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
},
{
    "productID": 25,
    "productName": "Lemon Rice",
    "ownerID": "rbusiness@919840573702",
    "discription": "from REC Cafe",
    "category": "lunch",
    "price": 30,
    "discount":0,
    "isavailable": true,
    "quantity": 50,
    "imageUrl": "lemon_rice.png",
    "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
},
{
    "productID": 26,
    "productName": "Omelette",
    "ownerID": "rbusiness@919840573702",
    "discription": "from REC Cafe",
    "category": "lunch",
    "price": 15,
    "discount":0,
    "isavailable": true,
    "quantity": 50,
    "imageUrl": "omelette.png",
    "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
},
{
    "productID": 27,
    "productName": "Boiled Egg",
    "ownerID": "rbusiness@919840573702",
    "discription": "from REC Cafe",
    "category": "lunch",
    "price": 10,
    "discount":0,
    "isavailable": true,
    "quantity": 50,
    "imageUrl": "boiled_egg.png",
    "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
},
{
    "productID": 28,
    "productName": "Rose Milk",
    "ownerID": "rbusiness@919840573702",
    "discription": "from REC Cafe",
    "category": "snacks",
    "price": 20,
    "discount":0,
    "isavailable": true,
    "quantity": 50,
    "imageUrl": "rosemilk.png",
    "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
},
{
    "productID": 29,
    "productName": "Lemon Juice",
    "ownerID": "rbusiness@919840573702",
    "discription": "from REC Cafe",
    "category": "snacks",
    "price": 15,
    "discount":0,
    "isavailable": true,
    "quantity": 50,
    "imageUrl": "lemonjuice.png",
    "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
},
{
    "productID": 30,
    "productName": "Samosa(1 Nos)",
    "ownerID": "rbusiness@919840573702",
    "discription": "from REC Cafe",
    "category": "snacks",
    "price": 10,
    "discount":0,
    "isavailable": true,
    "quantity": 50,
    "imageUrl": "samosa.png",
    "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
},
{
    "productID": 31,
    "productName": "Bread Omelette",
    "ownerID": "rbusiness@919840573702",
    "discription": "from REC Cafe",
    "category": "snacks",
    "price": 5,
    "discount":0,
    "isavailable": true,
    "quantity": 50,
    "imageUrl": "bread_omelette.png",
    "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
},
{
    "productID": 32,
    "productName": "Veg Roll(1 Nos)",
    "ownerID": "rbusiness@919840573702",
    "discription": "from REC Cafe",
    "category": "snacks",
    "price": 20,
    "discount":0,
    "isavailable": true,
    "quantity": 50,
    "imageUrl": "veg_roll.png",
    "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
},
{
    "productID": 33,
    "productName": "Egg Roll (1 Nos)",
    "ownerID": "rbusiness@919840573702",
    "discription": "from REC Cafe",
    "category": "snacks",
    "price": 30,
    "discount":0,
    "isavailable": true,
    "quantity": 50,
    "imageUrl": "egg_roll.png",
    "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
},
{
    "productID": 34,
    "productName": "Veg Puff (1 Nos)",
    "ownerID": "rbusiness@919840573702",
    "discription": "from REC Cafe",
    "category": "snacks",
    "price": 15,
    "discount":0,
    "isavailable": true,
    "quantity": 50,
    "imageUrl": "veg_puff.png",
    "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
},
{
    "productID": 35,
    "productName": "Egg Puff(1 Nos)",
    "ownerID": "rbusiness@919840573702",
    "discription": "from REC Cafe",
    "category": "snacks",
    "price": 20,
    "discount":0,
    "isavailable": true,
    "quantity": 50,
    "imageUrl": "egg_puff.png",
    "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
},
{
    "productID": 36,
    "productName": "Corn Puffs",
    "ownerID": "rbusiness@919840573702",
    "discription": "from REC Cafe",
    "category": "snacks",
    "price": 10,
    "discount":0,
    "isavailable": true,
    "quantity": 50,
    "imageUrl": "cornpuff.png",
    "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
},
{
    "productID": 37,
    "productName": "Water Bottle (500 ML)",
    "ownerID": "rbusiness@919840573702",
    "discription": "from REC Cafe",
    "category": "snacks",
    "price": 10,
    "discount":0,
    "isavailable": true,
    "quantity": 50,
    "imageUrl": "water_bottle.png",
    "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
},
{
    "productID": 38,
    "productName": "Milk Shake",
    "ownerID": "rbusiness@919840573702",
    "discription": "from REC Cafe",
    "category": "snacks",
    "price": 35,
    "discount":0,
    "isavailable": true,
    "quantity": 50,
    "imageUrl": "shake.png",
    "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
},
{
    "productID": 39,
    "productName": "Too Yum (All Flavours)",
    "ownerID": "rbusiness@919840573702",
    "discription": "from REC Cafe",
    "category": "snacks",
    "price": 10,
    "discount":0,
    "isavailable": true,
    "quantity": 50,
    "imageUrl": "yum.png",
    "availableOn": ["monday,tuesday,wednesday,thursday,friday,saturday"]
}


]